<a href="https://colab.research.google.com/github/MaschinenNah/MachineLearningKochbuch03_LambdaSchichten/blob/main/LambdaAusdruecke04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensoren


In [ ]:
from keras.layers import Input, Lambda
from keras.models import Model
import numpy as np

In [ ]:
def predict_single(model, input):
  input = input[np.newaxis, ...]
  output = model.predict(input)[0]
  return output

In [ ]:
import tensorflow as tf

In [ ]:
input_layer = Input((3,3))
output_layer = tf.math.multiply(input_layer, input_layer)
model4 = Model(input_layer, output_layer)

model4.summary()

Model: "model_5"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_6 (InputLayer)            [(None, 3, 3)]       0                                            
__________________________________________________________________________________________________
tf.math.multiply (TFOpLambda)   (None, 3, 3)         0           input_6[0][0]                    
                                                                 input_6[0][0]                    
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________


In [ ]:
predict_single(model4, np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3)))

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

### Tensor reduce_sum

In [ ]:
input_layer = Input((3))
output_layer = tf.reduce_sum(input_layer, axis=1)
model5 = Model(input_layer, output_layer)

model5.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
tf.math.reduce_sum (TFOpLamb (None,)                   0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [ ]:
predict_single(model5, np.array([1.1,1.2,2.3]))

4.6000004

### Tensor reduce_sum 2

In [ ]:
input_layer = Input((3, 3))
output_layer = tf.reduce_sum(input_layer, axis=[1,2])
model5 = Model(input_layer, output_layer)

#model5.summary()

predict_single(model5, np.array([1,1,1,1,1,1,1,1,1]).reshape((3,3)))

9.0

### Tensor reduce_sum 3

In [ ]:
input_layer = Input((3, 3, 3))
output_layer = tf.reduce_sum(input_layer, axis=[1])
model5 = Model(input_layer, output_layer)

#model5.summary()

input_ = np.ones((3,3,3))
input_ = np.array([10,20,30,40,50,60,70,80,90,10,20,30,40,50,60,70,80,90,10,20,30,40,50,60,70,80,90]).reshape((3,3,3))
print(input_)
predict_single(model5, input_)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


array([[ 30.,  60.,  90.],
       [120., 150., 180.],
       [210., 240., 270.]], dtype=float32)

In [ ]:
arr = np.zeros((3,3,3), dtype="uint8")
arr.fill(17)
arr

array([[[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17]],

       [[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17]],

       [[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17]]], dtype=uint8)