<a href="https://colab.research.google.com/github/MaschinenNah/MachineLearningKochbuch03_LambdaSchichten/blob/main/LambdaAusdruecke04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensoren


In [1]:
from keras.layers import Input, Lambda
from keras.models import Model
import numpy as np

In [2]:
def predict_single(model, input):
  input = input[np.newaxis, ...]
  output = model.predict(input)[0]
  return output

In [5]:
import tensorflow as tf

In [10]:
input_layer = Input((3,3))
output_layer = tf.math.multiply(input_layer, input_layer)
model4 = Model(input_layer, output_layer)

model4.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 3, 3)]            0         
_________________________________________________________________
tf.math.multiply_3 (TFOpLamb (None, 3, 3)              0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [11]:
predict_single(model4, np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3)))

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]], dtype=float32)

### Tensor reduce_sum

In [12]:
input_layer = Input((3))
output_layer = tf.reduce_sum(input_layer, axis=1)
model5 = Model(input_layer, output_layer)

model5.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
tf.math.reduce_sum (TFOpLamb (None,)                   0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [13]:
predict_single(model5, np.array([1.1,1.2,2.3]))

4.6000004

### Tensor reduce_sum 2

In [45]:
input_layer = Input((3, 3))
output_layer = tf.reduce_sum(input_layer, axis=[1])
model5 = Model(input_layer, output_layer)

#model5.summary()

arr = np.array([1,1,1,0,0,0,2,2,2]).reshape((3,3))

print(arr)

print(predict_single(model5, arr))
print(predict_single(model5, arr).shape)

[[1 1 1]
 [0 0 0]
 [2 2 2]]
[3. 3. 3.]
(3,)


### Tensor reduce_sum 3

In [52]:
input_layer = Input((3, 3, 3))
output_layer = tf.reduce_sum(input_layer, axis=[3])
model5 = Model(input_layer, output_layer)

#model5.summary()

input_ = np.ones((3,3,3))
input_ = np.array([110,120,130,140,150,160,170,180,190,210,220,230,240,250,260,270,280,290,310,320,330,340,350,360,370,380,390]).reshape((3,3,3))
print(input_)
predict_single(model5, input_)

[[[110 120 130]
  [140 150 160]
  [170 180 190]]

 [[210 220 230]
  [240 250 260]
  [270 280 290]]

 [[310 320 330]
  [340 350 360]
  [370 380 390]]]


array([[ 360.,  450.,  540.],
       [ 660.,  750.,  840.],
       [ 960., 1050., 1140.]], dtype=float32)

In [ ]:
arr = np.zeros((3,3,3), dtype="uint8")
arr.fill(17)
arr

array([[[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17]],

       [[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17]],

       [[17, 17, 17],
        [17, 17, 17],
        [17, 17, 17]]], dtype=uint8)