<a href="https://colab.research.google.com/github/MaschinenNah/MachineLearningKochbuch03_LambdaSchichten/blob/main/LambdaAusdruecke02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lambda Schichten 02 


In [39]:
from keras.layers import Input, Lambda
from keras.models import Model
import numpy as np
import tensorflow as tf

# Hier kommen einige unwichtige und störende Warnungen, deshalb:
import warnings
warnings.filterwarnings('ignore')

# Weil Modelle immer Batches verarbeiten, 
# wir uns aber erst einmal einzelne Beispiele anschauen wollen:
def predict_single(model, input):
  input = input[np.newaxis, ...]
  output = model.predict(input)[0]
  return output

### Eine Lambda Schicht, die auf jeden Input 1 addiert

In [22]:
input_layer = Input((3))
output_layer = Lambda(lambda n : n+1)(input_layer)
model = Model(input_layer, output_layer)
model.summary()

Model: "model_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 3)]               0         
_________________________________________________________________
lambda_9 (Lambda)            (None, 3)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [25]:
predict_single(model, np.array([1,1,1]))

array([2., 2., 2.], dtype=float32)

In [24]:
predict_single(model, np.array([1,2,3]))

array([2., 3., 4.], dtype=float32)

### Eine Lambda Schicht, die jeden Input rundet:





In [42]:
input_layer = Input((3))
output_layer = Lambda(lambda n : tf.where(n < 0.5, 0, 1))(input_layer)
model = Model(input_layer, output_layer)
model.summary()

Model: "model_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_20 (InputLayer)        [(None, 3)]               0         
_________________________________________________________________
lambda_19 (Lambda)           (None, 3)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [43]:
predict_single(model, np.array([0.1, 0.5, 0.3]))

array([0, 1, 0], dtype=int32)